### ISSUE TITLE
GLPI 9.3

### ISSUE THREAD

**Issue by rcfloresh** [FutureProcessing/glpi-fpsaml#8]
Do you have some updates to GLPI 9.3??

**Comment by derricksmith** [comment]
I have this working on 9.3

You need to change the plugin_fpsaml_check_prerequisites function in setup.php to allow the plugin to work.  I changed to : 
if (version_compare(GLPI_VERSION, '0.84', 'lt') || version_compare(GLPI_VERSION, '9.4.0', 'gt')) {

Otherwise, everything appears to be working correctly.

**Comment by rcfloresh** [comment]
Thank you, so much... @derricksmith , I have a question.. May you help to me to setup this plugin? please.

**Comment by derricksmith** [comment]
You need to configure cfg.php with the proper information.  What SP are you using for SAML?

**Comment by rcfloresh** [comment]
I'm using Google like SP. And I have the pem and xml file... the crt file I was create it using ssl command and the pem file

**Comment by derricksmith** [comment]
Sorry, I am only familiar with ADFS

**Comment by Kailas10** [comment]
I'm using ADFS after authentication the SAMl response handled in acs.php file. but the user is not exist in GLPI.
So, how can I create a new user if its not exist in GLPI users?

**Comment by fullmetalucard** [comment]
Hi there,

Same problem here.
I tried to install the plugin on a 6.3.1 GLPI and tried the trick on the setup.php file, but the plugin still doesn't appear in the plugins' list. cfg.ph is configured. I'm not using ADFS for remote IDP but i'm very familiar with SAML authentication. Could you please detail what you did to make it work with a 9.3 version ?

Thanks

**Comment by fullmetalucard** [comment]
Hi,

I'm still facing the problem. Plugin doesn't appear in plugins' lit.
Is there a way to debug and find what's going on ?

My env:

Debian 9.5
PHP: PHP 7.0.30-0+deb9u1
GLPI : 9.3.1

**Comment by derricksmith** [comment]
> 
> 
> I'm using ADFS after authentication the SAML response handled in acs.php file. but the user is not exist in GLPI.
> So, how can I create a new user if its not exist in GLPI users?

I had LDAP integrated also, which created previously unknown users in GLPI.  Not sure this plugin has this capability on its own.

**Comment by derricksmith** [comment]
FYI, for numerous reasons I have stopped using this plugin.  Mainly, the configuration is somewhat complex and required additional changes to core files in order to make work in my environment.  In the end, I created my own plugin using the One-Login SAML library.  Plugin is alpha at best but I welcome any suggestions or comments at https://github.com/derricksmith/phpsaml.

**Comment by pablitobin** [comment]
@derricksmith do you know how to configure to use with Azure AD?

**Comment by derricksmith** [comment]
@pablitobin, I stopped using fpsaml in favor of my own plugin but have since eliminated GLPI from my environment.  The Azure configuration is fairly similar for all SAML applications and there are a number of tutorials available.  You will point the Azure Enterprise App to the acs.php URL for your GLPI environment.

**Comment by pablitobin** [comment]
@derricksmith Do you have any tutorial? I try to configure but It does not work. May be you have some examples or a step-by-step how to fill each field?

**Comment by derricksmith** [comment]
I don't, you can try Google.  Make sure you are using a proper certificate on your web host.  Self-signed certs will cause problems.

**Comment by prybak** [comment]
This has been resolved by lastest updates.
